---
# TODO: Figure out a way to cache the long boolean expression into a variable instead of copy-pasting it

- name: Running simple_compose for Compose projects
  loop: "{{ simple_compose_projects }}"
  loop_control:
    loop_var: project
  when: simple_compose_projects is defined and simple_compose_projects | length > 0 and simple_compose_username is defined
  ansible.builtin.include_tasks: "setup_project.yml"

- name: Inform the user that simple_compose is not configured
  when: not (simple_compose_projects is defined and simple_compose_projects | length > 0 and simple_compose_username is defined)
  ansible.builtin.fail:
    msg: "No simple_compose projects are defined, role execution failed!"

