---
- name: Ensure {{ project.name }} project directory exists and is owned by user "{{ simple_compose_username }}" # noqa name[template]
  ansible.builtin.file:
    path: "{{ project.directory }}"
    state: directory
    owner: "{{ simple_compose_username }}"
    group: "{{ simple_compose_username }}"
    mode: "0700"

- name: Copy project files for "{{ project.name }}"
  ansible.builtin.template:
    dest: "{{ project.directory }}/{{ item }}"
    src: "templates/{{ project.name }}/{{ item }}.j2"
    owner: "{{ simple_compose_username }}"
    group: "{{ simple_compose_username }}"
    mode: "0400"
  loop: "{{ project.files }}" 

- name: Bring up compose project using v2 for "{{ project.name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ project.directory }}"
