---
driver:
  name: docker
platforms:
  - name: instance
    # Geerlingguy to the rescue. This image includes a lot of useful tools for testing, like systemd.
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    # Start with systemd as the init system
    command: /usr/sbin/init
    # systemd relevant stuff
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

